name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}
authors: [${authors}]
main: ${groupId}.${artifactId}.${mainClass}

commands:
  stablemaster:
    description: Stablemaster command
    usage: /<command>
    aliases: [sm]

permissions:
  stablemaster.addrider:
    description: Allows user to add a rider to a horse
    default: true
  stablemaster.calm:
    description: Calms all your nearby animals
    default: true
  stablemaster.delrider:
    description: Allows user to remove a rider from a horse
    default: true
  stablemaster.give:
    description: Allows user to give animal to a new owner
    default: true
  stablemaster.help:
    description: Allows user to run the help command
    default: true
  stablemaster.info:
    description: Get info on an animal
    default: true
  stablemaster.release:
    description: Allows user to un-tame their animal
    default: op
  stablemaster.reload:
    description: Allows user to reload the configuration files
    defailt: op
  stablemaster.rename:
    description: Allows user to rename an animal
    default: op
  stablemaster.rename.colors:
    description: Allows colors in animals names
    default: op
  stablemaster.sit:
    description: Allows user to forcibly ride their animal
    default: op
  stablemaster.teleport:
    description: Allows user to teleport their animal
    default: op
  stablemaster.bypass:
    description: Allows user to interact with all animals
    default: op
    children:
      stablemaster.bypass.protection: true
      stablemaster.bypass.ride: true
      stablemaster.bypass.command.addrider: true
      stablemaster.bypass.command.calm: true
      stablemaster.bypass.command.delrider: true
      stablemaster.bypass.command.give: true
      stablemaster.bypass.command.info: true
      stablemaster.bypass.command.release: true
      stablemaster.bypass.command.rename: true
      stablemaster.bypass.command.sit: true
      stablemaster.bypass.command.teleport: true
  stablemaster.tame:
    description: Allows user to tame an animal
    default: true
    children:
      stablemaster.tame.donkey: true
      stablemaster.tame.horse: true
      stablemaster.tame.llama: true
      stablemaster.tame.mule: true
      stablemaster.tame.ocelot: true
      stablemaster.tame.parrot: true
      stablemaster.tame.skeleton_horse: true
      stablemaster.tame.zombie_horse: true
      stablemaster.tame.wolf: true